services:
  docker-logs-looker:
    image: ghcr.io/baxerus/docker-logs-looker:latest
    container_name: docker-logs-looker
    restart: always
    cpus: 0.25
    mem_limit: 100M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # - CONTAINER_LIST=aaa-example-service
      # - TAIL=10
      - TIMESTAMPS=enable
    ports:
      - 1234:8080
